# Generated by Django 5.2.6 on 2025-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('driver', 'Driver'), ('admin', 'Admin')], default='regular', max_length=10),
        ),
    ]
