# Generated by Django 5.2 on 2025-10-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuprequest',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('enroute', 'En Route'), ('done', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='waste_type',
            field=models.CharField(choices=[('regular', 'Regular Waste'), ('bulky', 'Bulky Waste')], default='regular', max_length=16),
        ),
    ]
