# Generated by Django 5.2 on 2025-10-01 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pickuprequest_options_pickuprequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complaint_type', models.CharField(choices=[('missed_pickup', 'Missed Pickup'), ('damage', 'Property Damage'), ('billing', 'Billing Issue'), ('driver', 'Driver Concern'), ('other', 'Other')], max_length=30)),
                ('subject', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('status', models.CharField(default='open', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RecyclingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(choices=[('paper', 'Paper/Cardboard'), ('plastic', 'Plastics'), ('metal', 'Metals'), ('glass', 'Glass'), ('ewaste', 'E-waste'), ('battery', 'Batteries'), ('other', 'Other')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recycle_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReuseDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('clothing', 'Clothing'), ('appliance', 'Appliance'), ('books', 'Books'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('partner', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reuse_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuse_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('pickup', 'Pickup'), ('recycling', 'Recycling'), ('reuse', 'Reuse'), ('complaint', 'Complaint Resolution'), ('bonus', 'Bonus')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('memo', models.CharField(blank=True, default='', max_length=160)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
