# Generated by Django 5.2 on 2025-10-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_complaint_recyclinglog_reusedonation_rewardevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusedonation',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
