# Generated by Django 5.2 on 2025-10-03 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_reusedonation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusedonation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuses_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reusedonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('donated', 'Donated'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reusedonation',
            index=models.Index(fields=['status', '-created'], name='users_reuse_status_1d6576_idx'),
        ),
    ]
