# Generated by Django 5.2 on 2025-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reusedonation_accepted_by_reusedonation_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reusedonation',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_by__isnull', True), models.Q(('accepted_by', models.F('user')), _negated=True), _connector='OR'), name='reuse_accepted_by_not_self'),
        ),
        migrations.AddConstraint(
            model_name='reusedonation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), ('accepted_by__isnull', True), _connector='OR'), name='reuse_accepted_by_null_when_pending'),
        ),
        migrations.AddConstraint(
            model_name='reusedonation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'accepted'), _negated=True), ('accepted_by__isnull', False), _connector='OR'), name='reuse_accepted_by_set_when_accepted'),
        ),
    ]
