# Generated by Django 5.2 on 2025-10-05 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_reusedonation_reuse_accepted_by_not_self_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reusedonation',
            name='reuse_accepted_by_null_when_pending',
        ),
        migrations.RemoveConstraint(
            model_name='reusedonation',
            name='reuse_accepted_by_set_when_accepted',
        ),
        migrations.RemoveIndex(
            model_name='reusedonation',
            name='users_reuse_status_1d6576_idx',
        ),
        migrations.AddField(
            model_name='reusedonation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the item was accepted (if accepted).', null=True),
        ),
        migrations.AlterField(
            model_name='reusedonation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='User who accepted the item (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuses_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reusedonation',
            index=models.Index(fields=['status', 'created'], name='users_reuse_status_afe6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='reusedonation',
            index=models.Index(fields=['status', 'accepted_at'], name='users_reuse_status_5fdcc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='reusedonation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), models.Q(('accepted_by__isnull', True), ('accepted_at__isnull', True)), _connector='OR'), name='reuse_accept_fields_null_when_pending'),
        ),
        migrations.AddConstraint(
            model_name='reusedonation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'accepted'), _negated=True), models.Q(('accepted_by__isnull', False), ('accepted_at__isnull', False)), _connector='OR'), name='reuse_accept_fields_set_when_accepted'),
        ),
    ]
