# Generated by Django 5.2 on 2025-10-06 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_deliverytask_drivercomplaint_driverlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='users.deliverytask'),
        ),
        migrations.DeleteModel(
            name='DriverComplaint',
        ),
    ]
