# Generated by Django 5.2 on 2025-10-06 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_complaint_driver_complaint_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_complaints_general_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='assigned_to',
            field=models.ForeignKey(help_text='Driver user', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_delivery_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DriverActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='event', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('row', models.CharField(default='info', max_length=16)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='DriverComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Service', max_length=80)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='open', max_length=20)),
                ('when_dt', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='driver_complaints/')),
                ('against_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complained_by_driver', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when_dt'],
            },
        ),
        migrations.CreateModel(
            name='DriverReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('points', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DriverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('when_dt', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='assigned', max_length=16)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='driver_tasks/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when_dt', '-created'],
            },
        ),
    ]
