# Generated by Django 5.2 on 2025-10-07 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_complaint_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertask',
            name='driver',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='drivercomplaint',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_complaint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drivercomplaint',
            name='photo',
            field=models.ImageField(blank=True, upload_to='driver_complaint/'),
        ),
        migrations.AlterField(
            model_name='recyclinglog',
            name='material',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='DriverReward',
        ),
        migrations.DeleteModel(
            name='DriverTask',
        ),
    ]
