# Generated by Django 5.2 on 2025-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_drivertask_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardevent',
            name='source',
            field=models.CharField(choices=[('recycling', 'Recycling'), ('reuse', 'Reuse')], max_length=20),
        ),
    ]
