# Generated by Django 5.2 on 2025-10-08 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_rewardevent_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverpointevent',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='driverpointevent',
            name='updated',
        ),
        migrations.AddField(
            model_name='driverpointevent',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='driverpointevent',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_point_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverpointevent',
            name='reason',
            field=models.CharField(default='delivery', max_length=40),
        ),
    ]
