# Generated by Django 5.2 on 2025-10-13 06:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_driverpointevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='date',
            field=models.DateField(validators=[users.models.validate_not_past_date]),
        ),
    ]
